dev: 
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: root
      port: 5432
      dbname: postgres
      schema: dev

prd: 
  target: prd
  outputs:
    prd:
      type: postgres
      host: localhost
      user: postgres
      password: root
      port: 5432
      dbname: postgres
      schema: prd